version: '2'
services:

  redis:
    image: "redis:alpine"
    container_name: dinpay-redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: "postgres:alpine"
    container_name: dinpay-postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: dinpay_testnet
     POSTGRES_USER: dinpay

  dinpay-base:
    build: .
    image: dinpay-base
    container_name: dinpay-base
    ports:
     - "66141:66141"
     - "66143:66143"
    volumes:
     - dinpay-base:/dinpay-base
    tty: true
    privileged: true
    links:
     - postgres
     - redis
    depends_on:
      - postgres
      - redis
    command:
      - /bin/sh
      - -c
      - |
          /entrypoint.sh

volumes:
  redis:
  postgres:
  dinpay-base:
    driver_opts:
      type: none
      device: $PWD/../../
      o: bind
